# Generated by Django 5.0.2 on 2024-03-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='experience_certificate',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mbbs_certificate',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
