# Generated by Django 5.0.2 on 2024-04-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_docspecialisation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('article', models.FileField(blank=True, null=True, upload_to='blogpost/')),
                ('video', models.FileField(blank=True, null=True, upload_to='blogpost/')),
            ],
        ),
    ]
