# Generated by Django 5.0.3 on 2024-03-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_customuser_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.specialisation'),
        ),
    ]
