# Generated by Django 5.0.3 on 2024-03-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_specialisation_alter_customuser_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.specialisation'),
        ),
    ]
