# Generated by Django 5.0.3 on 2024-04-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_carousalimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarousalImage',
        ),
    ]
