# Generated by Django 5.0.2 on 2024-04-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
