# Generated by Django 5.0.2 on 2024-04-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_timeslot_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
    ]
