# Generated by Django 5.0.2 on 2024-04-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_remove_timeslot_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profilepic/'),
        ),
    ]
