# Generated by Django 5.0.2 on 2024-04-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_timeslot_available_timeslot_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
    ]
