# Generated by Django 5.0.3 on 2024-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
