# Generated by Django 5.0.3 on 2024-04-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_timeslot_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
