# Generated by Django 5.0.3 on 2024-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_customuser_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
