# Generated by Django 5.0.3 on 2024-04-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_blogpost_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_verified',
            field=models.CharField(default=True),
        ),
    ]
