# Generated by Django 5.0.3 on 2024-04-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_blogpost_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
