# Generated by Django 5.0.2 on 2024-04-13 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_alter_blogpost_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consultation_fee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
