# Generated by Django 5.0.2 on 2024-04-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_customuser_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
