# Generated by Django 5.0.3 on 2024-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_slotbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
