# Generated by Django 5.0.2 on 2024-04-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
